// Pure helpers for the thumbnail-titles functions, shared with the unit test.
//
// The spec is the retired n8n step "Generate Titles" (workflow VIDEO
// PRODUCTION AUTOMATION, webhook graphic-form), read only on 2026-10-09: it
// downloaded the client's filming plan and asked Claude for a 2 to 5 word
// title per video, which became the thumbnail sub-issue's description. It
// stopped when batches moved into SyncView (commit 598371e9, 2026-09-22).
// Nothing here talks to the network or the database.

// The n8n node's own instruction, kept word for word where it still applies.
// The video list, the filming plan and the answer format are appended by the
// function (like the transcript after a caption prompt), so a person editing
// the prompt only ever edits the instructions.
export const N8N_TITLE_PROMPT = [
  "You write short, punchy reel titles.",
  "",
  "For each video, write a title (2-5 words) using this approach:",
  "- Find the most quotable, surprising, or emotionally punchy phrase in that video",
  "- Either quote it directly or distill it to its sharpest form",
  "- NO descriptions, NO filler words, NO clinical language",
].join("\n");

export const STYLE_HEADER = "This client's title style, from the Synchro Brain voice file:";
export const STYLE_MAX_CHARS = 5000;
// Facts about how the client talks to the agency, not how their content reads.
export const STYLE_EXCLUDE = /communication|talks? to us|relationship|source status|historical/i;

// The default prompt for one client: the n8n instruction, then the client's
// written title style when the Brain has one. Staff edit the result.
export function defaultPromptFor(styleText) {
  const style = String(styleText || "").trim().slice(0, STYLE_MAX_CHARS).trim();
  return style ? `${N8N_TITLE_PROMPT}\n\n${STYLE_HEADER}\n\n${style}` : N8N_TITLE_PROMPT;
}

// The prompt actually used: what staff saved, else the seeded default, else
// the plain n8n instruction.
export function effectivePrompt(row) {
  const saved = String((row && row.prompt) || "").trim();
  if (saved) return saved;
  const seeded = String((row && row.default_prompt) || "").trim();
  return seeded || N8N_TITLE_PROMPT;
}

// Labelled exactly as the Submit tab's generated line is, so a designer can
// always tell a machine line from one a person wrote.
export const AI_LABEL = "Thumbnail title (generated by AI): ";
export const NEEDS_INFO = "Needs info: ";
export const MIN_PLAN_CHARS = 300;
export const MAX_TITLE_CHARS = 80;
export const MAX_TITLE_WORDS = 8;

export const NEEDS_INFO_TEXT = Object.freeze({
  no_plan: "no filming plan is linked to this client in SyncView, so no thumbnail title was written. Add the title here by hand.",
  plan_unreadable: "the client's filming plan could not be opened (it may not be shared by link), so no thumbnail title was written. Add the title here by hand.",
  plan_empty: "the client's filming plan is empty, so no thumbnail title was written. Add the title here by hand.",
  no_month_tab: "the client's filming plan has no tab for {month}, so no thumbnail title was written. Add the title here by hand.",
  no_match: "this post could not be matched to a video in the filming plan{post}, so no thumbnail title was written. Add the title here by hand.",
  not_grounded: "the suggested title did not use the filming plan's own words, so it was not used. Add the title here by hand.",
  generation_failed: "a thumbnail title could not be generated after several tries. Add the title here by hand.",
});

export function needsInfoLine(code, vars = {}) {
  let text = NEEDS_INFO_TEXT[code] || NEEDS_INFO_TEXT.generation_failed;
  text = text.replace("{month}", String(vars.month || "this month"));
  const post = String(vars.post || "").replace(/[\r\n]+/g, " ").trim().slice(0, 80);
  text = text.replace("{post}", post ? ` (post "${post}")` : "");
  return NEEDS_INFO + text;
}

export function titleLine(title) {
  return AI_LABEL + String(title || "").trim();
}

// "Video 4", "Video 4 — Launch", "Reel #4", "VIDEO4- ADS" -> 4.
export function numberFromCardName(name) {
  const m = /^\s*(?:video|vid|reel|short)\s*#?\s*(\d{1,3})(?!\d)/i.exec(String(name || ""));
  return m ? Number(m[1]) : null;
}

// A bare "Thumbnail 4" (or "Sample Thumbnail 4") inside a batch of several
// posts is the Submit tab's video number. A single-post batch numbers its
// one item 1 whatever the post is, so that 1 says nothing about the plan.
export function numberFromItemTitle(title, thumbnailsInBatch) {
  if (!(Number(thumbnailsInBatch) > 1)) return null;
  const m = /^\s*(?:sample\s+)?thumbnail\s+(\d{1,3})\s*$/i.exec(String(title || ""));
  return m ? Number(m[1]) : null;
}

// The name part of "Thumbnail 4 — Launch hook" or of the card name, for the
// model to match by topic when there is no number.
export function postNameFor(cardName, itemTitle) {
  const card = String(cardName || "").trim();
  if (card) return card.slice(0, 200);
  const m = /^\s*(?:sample\s+)?thumbnail\s+\d+\s*[—–-]\s*(.+)$/i.exec(String(itemTitle || ""));
  return m ? m[1].trim().slice(0, 200) : "";
}

export const MONTHS = ["january", "february", "march", "april", "may", "june", "july",
  "august", "september", "october", "november", "december"];

export function monthLabel(date) {
  const d = new Date(date);
  if (Number.isNaN(d.getTime())) return "";
  const m = MONTHS[d.getUTCMonth()];
  return m[0].toUpperCase() + m.slice(1) + " " + d.getUTCFullYear();
}

// Pick the filming-plan tab for the month the post was created in. The house
// format keeps one Docs tab per month. A tab whose NAME carries the month (and
// the year, when the name has one) wins; then the month the tab's text talks
// about most; then, when the Doc has a single tab, that tab. A month with no
// tab is reported, never guessed: a wrong tab means a wrong video.
export function pickTab(tabs, createdAt, tabMonthOf) {
  const list = (tabs || []).filter((t) => String(t.text || "").trim());
  if (!list.length) return { tab: null, reason: "plan_empty" };
  const d = new Date(createdAt);
  const month = MONTHS[Number.isNaN(d.getTime()) ? new Date().getUTCMonth() : d.getUTCMonth()];
  const year = String(Number.isNaN(d.getTime()) ? new Date().getUTCFullYear() : d.getUTCFullYear());
  const yearOk = (label) => {
    const years = String(label || "").match(/\b20\d\d\b/g);
    return !years || years.includes(year);
  };
  const byName = list.filter((t) => String(t.name || "").toLowerCase().includes(month) && yearOk(t.name));
  if (byName.length === 1) return { tab: byName[0], reason: "" };
  if (byName.length > 1) {
    const exactYear = byName.filter((t) => String(t.name).includes(year));
    if (exactYear.length === 1) return { tab: exactYear[0], reason: "" };
  }
  const byText = list.filter((t) => {
    const label = String((tabMonthOf ? tabMonthOf(t.text) : "") || "").toLowerCase();
    return label.startsWith(month) && yearOk(label);
  });
  if (byText.length === 1) return { tab: byText[0], reason: "" };
  if (list.length === 1) return { tab: list[0], reason: "" };
  return { tab: null, reason: "no_month_tab" };
}

const STOPWORDS = new Set([
  "a", "an", "and", "are", "as", "at", "be", "but", "by", "can", "for", "from",
  "has", "have", "how", "in", "into", "is", "it", "its", "of", "on", "or", "that",
  "the", "their", "them", "then", "they", "this", "to", "was", "were", "what",
  "when", "which", "why", "will", "with", "you", "your", "not", "dont", "just",
  "more", "most", "than", "about", "every", "never", "always",
]);

export function normalizedText(value) {
  return String(value || "").toLowerCase().replace(/[’']/g, "").replace(/[^a-z0-9\s]+/g, " ").replace(/\s+/g, " ");
}

// Grounding, loosened from the Submit tab's all-words rule because the n8n
// instruction asks the model to DISTILL a phrase, not only quote it: at least
// half of the title's significant words, and at least one, must already appear
// in the filming plan. An invented line (the 2026-08-17 incident: colours,
// wardrobe, camera direction) shares almost no words with a plan and fails.
export function grounded(title, planNormalized) {
  const significant = normalizedText(title).split(" ")
    .filter((w) => w.length >= 4 && !STOPWORDS.has(w));
  if (!significant.length) return false;
  const hits = significant.filter((w) => planNormalized.includes(w.replace(/s$/, ""))).length;
  return hits >= 1 && hits * 2 >= significant.length;
}

export function titleShapeOk(title) {
  const t = String(title || "").trim();
  if (!t || t.length > MAX_TITLE_CHARS || /[\r\n]/.test(t)) return false;
  return t.split(/\s+/).length <= MAX_TITLE_WORDS;
}

export const SYSTEM_PROMPT = [
  "You title thumbnails for a social media agency from a client's filming plan.",
  "The user message gives the client's title instructions, a list of posts and the filming plan.",
  "",
  "Matching each post to a video in the plan:",
  "- When a post has a videoNumber, it is that video counted sequentially from the top of the plan. The plan's own numbering may restart or be inconsistent; ignore it.",
  "- When a post has no videoNumber, match it by its postName to the one video whose topic it clearly names.",
  "- If a post cannot be matched with confidence, leave it out. Leaving it out is always better than guessing.",
  "",
  "Write only from what the plan says about that video. Never invent facts, names, places, colours, wardrobe or any art direction.",
  "",
  'Respond ONLY with valid JSON, an array like [{"key": "p1", "title": "Your Title Here"}]. Use the keys you were given.',
].join("\n");

export function userMessage(prompt, posts, planText) {
  const list = posts.map((p) => JSON.stringify({
    key: p.key,
    ...(p.videoNumber ? { videoNumber: p.videoNumber } : {}),
    ...(p.postName ? { postName: p.postName } : {}),
  })).join("\n");
  return `${prompt}\n\nPosts to title:\n${list}\n\nFilming plan:\n${String(planText || "").slice(0, 20000)}`;
}

// Read the model's answer into key -> title. Anything malformed is ignored.
export function parseTitles(content, keys) {
  const text = (Array.isArray(content) ? content : [])
    .filter((part) => part && part.type === "text")
    .map((part) => String(part.text || ""))
    .join("\n")
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/, "")
    .trim();
  let parsed = null;
  try { parsed = JSON.parse(text); } catch (_e) {
    const a = text.indexOf("["), b = text.lastIndexOf("]");
    if (a >= 0 && b > a) { try { parsed = JSON.parse(text.slice(a, b + 1)); } catch (_e2) { parsed = null; } }
  }
  const wanted = new Set(keys);
  const out = new Map();
  if (!Array.isArray(parsed)) return { ok: false, titles: out };
  for (const row of parsed) {
    const key = row && typeof row.key === "string" ? row.key : "";
    const title = row && typeof row.title === "string" ? row.title.trim().replace(/^["“]|["”]$/g, "").trim() : "";
    if (!wanted.has(key) || !title || out.has(key)) continue;
    out.set(key, title);
  }
  return { ok: true, titles: out };
}

// The line written for one post, given the model's title (or none).
export function resolveLine(post, title, planNormalized) {
  if (!title) return { state: "needs_info", outcome: "no_match", text: needsInfoLine("no_match", { post: post.postName }) };
  if (!titleShapeOk(title) || !grounded(title, planNormalized)) {
    return { state: "needs_info", outcome: "not_grounded", text: needsInfoLine("not_grounded") };
  }
  return { state: "written", outcome: "title", text: titleLine(title) };
}

// A flag value is {"clients": [...]} where "*" means every client.
export function clientOn(flagValue, slug) {
  const clients = flagValue && Array.isArray(flagValue.clients) ? flagValue.clients : [];
  return clients.includes("*") || clients.includes(String(slug || ""));
}
