-- F39/F42/F43: canonical Production comment authorization, card-thread
-- crosswalk/import, and idempotent lifecycle CAS.
--
-- SOURCE ONLY in this slice. Do not apply without the owner-approved migration
-- gate, production-write/production-comments deployment, and TEST drill.
--
-- This migration is additive. Comment add/edit/delete continue to use the
-- already-allowed mirror_outbox operation `comment`; resolve/reopen are native
-- lifecycle state with no applicable Linear mutation. The mirror_outbox CHECK
-- and the parked F27 enqueue allowlist therefore do not change.

begin;

create table if not exists public.production_comment_read_audit (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_key text not null,
  auth_kind text not null check (auth_kind in ('none', 'staff', 'client')),
  deliverable_id text,
  decision text not null check (decision in ('allow', 'deny')),
  reason text not null
);

create index if not exists production_comment_read_audit_occurred_idx
  on public.production_comment_read_audit (occurred_at desc);

alter table public.production_comment_read_audit enable row level security;
revoke all on table public.production_comment_read_audit from public, anon, authenticated;
grant select, insert on table public.production_comment_read_audit to service_role;
grant usage, select on sequence public.production_comment_read_audit_id_seq to service_role;

create table if not exists public.production_comment_read_budget (
  actor_key text not null,
  window_start timestamptz not null,
  requests integer not null check (requests > 0 and requests <= 120),
  primary key (actor_key, window_start)
);

alter table public.production_comment_read_budget enable row level security;
revoke all on table public.production_comment_read_budget from public, anon, authenticated;
grant select, insert, update on table public.production_comment_read_budget to service_role;

-- This budget is deliberately principal-wide, not target-scoped. It is taken
-- immediately after exact credential resolution and before target lookup, so
-- missing and cross-scope probes share one bounded lane. Denial audit writes
-- can therefore never be amplified by cycling deliverable ids.
create or replace function public.production_comment_read_budget_take(
  p_actor_key text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_actor text := nullif(btrim(p_actor_key), '');
  v_window timestamptz := to_timestamp(
    floor(extract(epoch from clock_timestamp()) / 300) * 300
  );
  v_requests integer;
begin
  if v_actor is null then
    raise exception 'invalid production comment read budget actor';
  end if;

  insert into public.production_comment_read_budget (
    actor_key, window_start, requests
  ) values (
    v_actor, v_window, 1
  )
  on conflict (actor_key, window_start) do update
    set requests = public.production_comment_read_budget.requests + 1
    where public.production_comment_read_budget.requests < 120
  returning requests into v_requests;

  if not found then
    return jsonb_build_object(
      'ok', true,
      'allowed', false,
      'remaining', 0,
      'retry_after_seconds', 300
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'allowed', true,
    'remaining', 120 - v_requests
  );
end;
$fn$;

revoke all on function public.production_comment_read_budget_take(text)
  from public, anon, authenticated;
grant execute on function public.production_comment_read_budget_take(text)
  to service_role;

-- Allowed target reads get one durable audit record. This function does not
-- own request budgeting: the gateway must take the principal-wide budget
-- before it performs target lookup.
create or replace function public.production_comment_read_authorize(
  p_actor_key text,
  p_auth_kind text,
  p_deliverable_id text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_actor text := nullif(btrim(p_actor_key), '');
  v_kind text := lower(nullif(btrim(p_auth_kind), ''));
  v_deliverable text := nullif(btrim(p_deliverable_id), '');
begin
  if v_actor is null or v_kind not in ('staff', 'client') or v_deliverable is null then
    raise exception 'invalid production comment read authorization';
  end if;

  insert into public.production_comment_read_audit (
    actor_key, auth_kind, deliverable_id, decision, reason
  ) values (
    v_actor, v_kind, v_deliverable, 'allow', 'target_authorized'
  );
  return jsonb_build_object('ok', true, 'authorized', true);
end;
$fn$;

revoke all on function public.production_comment_read_authorize(text, text, text)
  from public, anon, authenticated;
grant execute on function public.production_comment_read_authorize(text, text, text)
  to service_role;

create table if not exists public.production_comment_mutation_receipts (
  dedup_key text primary key,
  comment_id text not null references public.production_comments(id) on delete cascade,
  action text not null check (action in ('add', 'edit', 'delete', 'resolve', 'unresolve')),
  intent_fingerprint text not null,
  result_version integer not null check (result_version > 0),
  created_at timestamptz not null default now()
);

alter table public.production_comment_mutation_receipts enable row level security;
revoke all on table public.production_comment_mutation_receipts from public, anon, authenticated;
grant select, insert on table public.production_comment_mutation_receipts to service_role;

create table if not exists public.production_comment_card_links (
  source_surface text not null check (source_surface in ('calendar', 'sxr')),
  card_id text not null,
  component text not null,
  native_comment_id text not null,
  deliverable_id text not null references public.deliverables(id) on delete cascade,
  production_comment_id text not null references public.production_comments(id) on delete cascade,
  source_fingerprint text not null,
  imported_at timestamptz not null default now(),
  primary key (source_surface, card_id, component, native_comment_id),
  unique (production_comment_id)
);

create index if not exists production_comment_card_links_deliverable_idx
  on public.production_comment_card_links (deliverable_id, component, imported_at);

alter table public.production_comment_card_links enable row level security;
revoke all on table public.production_comment_card_links from public, anon, authenticated;
grant select, insert, update on table public.production_comment_card_links to service_role;

create table if not exists public.production_comment_import_conflicts (
  id bigint generated by default as identity primary key,
  import_run_id text not null,
  source_surface text not null,
  card_id text,
  component text,
  native_comment_id text,
  classification text not null check (
    classification in (
      'missing_card_id', 'missing_comment_id', 'missing_deliverable_id',
      'missing_client_slug', 'missing_parent', 'parent_cycle',
      'duplicate_identity', 'identity_collision',
      'invalid_comment', 'malformed_comment_field',
      'malformed_attachment_field', 'malformed_attachment_entry',
      'malformed_lifecycle_timestamp',
      'snapshot_contract_required', 'coverage_mismatch'
    )
  ),
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.production_comment_import_conflicts enable row level security;
revoke all on table public.production_comment_import_conflicts from public, anon, authenticated;
grant select, insert on table public.production_comment_import_conflicts to service_role;
grant usage, select on sequence public.production_comment_import_conflicts_id_seq to service_role;

create or replace function public.production_comment_mirror_applicable(
  p_test_only boolean,
  p_legacy_parity boolean
) returns boolean
language plpgsql
security definer
stable
set search_path = public
as $fn$
begin
  -- F2 controls drainer activity; off/missing/unreadable is a staged pause,
  -- never the retired epoch. F32 has not installed an explicit server-owned
  -- retirement signal, so every currently applicable comment mutation queues.
  return true;
end;
$fn$;

revoke all on function public.production_comment_mirror_applicable(boolean, boolean)
  from public, anon, authenticated;
grant execute on function public.production_comment_mirror_applicable(boolean, boolean)
  to service_role;

-- Replace the existing atomic add wrapper without changing the current mirror
-- epoch: add/reply always creates the one applicable `comment` intent. F2 may
-- pause its drain but cannot suppress its creation.
create or replace function public.production_comment_write(
  p_comment jsonb,
  p_event jsonb default '{}'::jsonb
) returns public.production_comments
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_comment jsonb := coalesce(p_comment, '{}'::jsonb);
  v_event jsonb := coalesce(p_event, '{}'::jsonb);
  v_outbound jsonb := coalesce(v_event->'outbound', '{}'::jsonb);
  v_result public.production_comments%rowtype;
  v_receipt public.production_comment_mutation_receipts%rowtype;
  v_target_id text;
  v_outbox_id bigint;
  v_payload jsonb;
  v_deliverable_id text := nullif(btrim(v_comment->>'deliverable_id'), '');
  v_batch_id text := nullif(btrim(v_comment->>'batch_id'), '');
  v_client_slug text;
  v_team text;
  v_fingerprint text := nullif(btrim(v_outbound->'payload'->>'_intent_fingerprint'), '');
  v_native_comment_id text := nullif(btrim(v_comment->>'native_comment_id'), '');
  v_existing_native_dedup text;
  v_requested_id text := coalesce(
    nullif(btrim(v_comment->>'id'), ''),
    nullif(btrim(v_comment->>'native_comment_id'), '')
  );
  v_dedup_key text := nullif(btrim(v_outbound->>'dedup_key'), '');
  v_test_only boolean := coalesce((v_outbound->>'test_only')::boolean, false);
  v_legacy_parity boolean := coalesce((v_outbound->>'legacy_parity')::boolean, false);
  v_mirror_applicable boolean;
begin
  if lower(coalesce(v_comment->>'operation', 'add')) <> 'add'
     or lower(coalesce(v_outbound->>'operation', 'comment')) <> 'comment'
     or v_requested_id is null or v_dedup_key is null or v_fingerprint is null then
    raise exception 'production comment add identity required';
  end if;
  v_target_id := coalesce(v_deliverable_id, v_batch_id);
  if v_target_id is null then raise exception 'production comment outbound target required'; end if;
  if v_deliverable_id is not null then
    select d.client_slug, d.team into v_client_slug, v_team
    from public.deliverables d where d.id = v_deliverable_id;
  else
    select b.client_slug, coalesce(b.team, nullif(v_outbound->>'team', ''))
      into v_client_slug, v_team
    from public.batches b where b.id = v_batch_id;
  end if;
  if v_client_slug is null or v_team is null then
    raise exception 'production comment outbound scope required';
  end if;
  perform public.production_assert_authority(
    v_client_slug, v_team, v_test_only, v_legacy_parity
  );
  v_mirror_applicable := public.production_comment_mirror_applicable(
    v_test_only, v_legacy_parity
  );

  select r.* into v_receipt
  from public.production_comment_mutation_receipts r
  where r.dedup_key = v_dedup_key;
  if found then
    if v_receipt.comment_id is distinct from v_requested_id
       or v_receipt.action <> 'add'
       or v_receipt.intent_fingerprint is distinct from v_fingerprint then
      raise exception 'idempotency_conflict';
    end if;
    select c.* into v_result from public.production_comments c
    where c.id = v_receipt.comment_id;
    if not found then raise exception 'idempotent_result_missing'; end if;
    return v_result;
  end if;

  if v_native_comment_id is not null then
    select c.idempotency_key into v_existing_native_dedup
    from public.production_comments c
    where c.native_comment_id = v_native_comment_id;
    if found and v_existing_native_dedup is distinct from v_dedup_key then
      raise exception 'idempotency_conflict';
    end if;
  end if;

  if v_mirror_applicable and public.production_outbox_replay(
    'comment', v_target_id, 'comment', v_client_slug, v_team,
    nullif(v_comment->>'author_name', ''), nullif(v_comment->>'role', ''),
    v_test_only, v_legacy_parity, v_fingerprint, v_dedup_key
  ) then
    select c.* into v_result
    from public.production_comments c
    where c.id = v_requested_id
       or c.native_comment_id = v_requested_id
       or c.idempotency_key = v_dedup_key
    order by case when c.id = v_requested_id then 0 else 1 end
    limit 1;
    if not found then raise exception 'idempotent_result_missing'; end if;
  else
    v_result := public.production_comment_upsert(v_comment, v_event - 'outbound');
  end if;

  insert into public.production_comment_mutation_receipts (
    dedup_key, comment_id, action, intent_fingerprint, result_version
  ) values (
    v_dedup_key, v_result.id, 'add', v_fingerprint, v_result.version
  )
  on conflict (dedup_key) do nothing;
  if not found then raise exception 'idempotency_conflict'; end if;

  if v_mirror_applicable then
    v_payload := coalesce(v_outbound->'payload', '{}'::jsonb)
      || jsonb_build_object(
        'action', 'add',
        'body', v_result.body,
        'comment_id', v_result.id
      );
    v_outbox_id := public.mirror_outbox_enqueue(
      p_entity := 'comment',
      p_entity_id := coalesce(v_result.deliverable_id, v_result.batch_id),
      p_operation := 'comment',
      p_payload := v_payload,
      p_dedup_key := v_dedup_key,
      p_source_edited_at := v_result.source_updated_at,
      p_client_slug := v_result.client_slug,
      p_team := v_result.team,
      p_actor := v_result.author_name,
      p_role := v_result.role,
      p_deliverable_id := v_result.deliverable_id,
      p_batch_id := v_result.batch_id,
      p_comment_id := v_result.id,
      p_depends_on_id := nullif(v_outbound->>'depends_on_id', '')::bigint,
      p_test_only := v_test_only
    );
    if v_legacy_parity then
      update public.mirror_outbox
      set legacy_parity = true, updated_at = now()
      where id = v_outbox_id;
    end if;
  end if;
  return v_result;
end;
$fn$;

revoke all on function public.production_comment_write(jsonb, jsonb)
  from public, anon, authenticated;
grant execute on function public.production_comment_write(jsonb, jsonb)
  to service_role;

-- Linear comment-create acknowledgement must bind the provider id before the
-- outbox row can terminalize. The outbox row itself proves the exact canonical
-- comment identity; retries are idempotent and a conflicting provider id fails.
create or replace function public.production_comment_bind_linear_id(
  p_comment_id text,
  p_linear_comment_id text,
  p_outbox_id bigint
) returns public.production_comments
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_comment_id text := nullif(btrim(p_comment_id), '');
  v_linear_id text := nullif(btrim(p_linear_comment_id), '');
  v_outbox public.mirror_outbox%rowtype;
  v_existing public.production_comments%rowtype;
  v_result public.production_comments%rowtype;
begin
  if v_comment_id is null or v_linear_id is null or p_outbox_id is null then
    raise exception 'production comment Linear binding identity required';
  end if;

  select o.* into v_outbox
  from public.mirror_outbox o
  where o.id = p_outbox_id
  for update;
  if not found
     or v_outbox.entity is distinct from 'comment'
     or v_outbox.operation is distinct from 'comment'
     or v_outbox.comment_id is distinct from v_comment_id
     or nullif(btrim(v_outbox.payload->>'comment_id'), '') is distinct from v_comment_id then
    raise exception 'production comment Linear binding outbox mismatch';
  end if;

  select c.* into v_existing
  from public.production_comments c
  where c.id = v_comment_id
  for update;
  if not found then raise exception 'production comment Linear binding target missing'; end if;
  if v_existing.linear_comment_id is not null then
    if v_existing.linear_comment_id is distinct from v_linear_id then
      raise exception 'production comment Linear binding conflict';
    end if;
    return v_existing;
  end if;
  perform 1
  from public.production_comments c
  where c.linear_comment_id = v_linear_id
    and c.id <> v_comment_id;
  if found then raise exception 'production comment Linear id already bound'; end if;

  v_result := public.production_comment_upsert(
    jsonb_build_object(
      'id', v_comment_id,
      'operation', 'link_linear',
      'linear_comment_id', v_linear_id
    ),
    jsonb_build_object(
      'source', 'outbound',
      'actor', 'SyncView Mirror',
      'role', 'system',
      'outbox_id', p_outbox_id
    )
  );
  if v_result.linear_comment_id is distinct from v_linear_id then
    raise exception 'production comment Linear binding failed';
  end if;
  return v_result;
end;
$fn$;

revoke all on function public.production_comment_bind_linear_id(text, text, bigint)
  from public, anon, authenticated;
grant execute on function public.production_comment_bind_linear_id(text, text, bigint)
  to service_role;

create or replace function public.production_comment_lifecycle_write(
  p_comment jsonb,
  p_event jsonb default '{}'::jsonb,
  p_expected_version integer default null,
  p_expected_updated_at timestamptz default null
) returns public.production_comments
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_comment jsonb := coalesce(p_comment, '{}'::jsonb);
  v_event jsonb := coalesce(p_event, '{}'::jsonb);
  v_outbound jsonb := coalesce(v_event->'outbound', '{}'::jsonb);
  v_action text := lower(coalesce(nullif(v_comment->>'operation', ''), ''));
  v_requested_id text := coalesce(
    nullif(btrim(v_comment->>'id'), ''),
    nullif(btrim(v_comment->>'native_comment_id'), '')
  );
  v_dedup_key text := nullif(btrim(v_outbound->>'dedup_key'), '');
  v_fingerprint text := nullif(btrim(v_outbound->'payload'->>'_intent_fingerprint'), '');
  v_legacy_parity boolean := coalesce((v_outbound->>'legacy_parity')::boolean, false);
  v_existing public.production_comments%rowtype;
  v_result public.production_comments%rowtype;
  v_receipt public.production_comment_mutation_receipts%rowtype;
  v_target_id text;
  v_payload jsonb;
  v_outbox_id bigint;
  v_dependency_id bigint;
  v_supplied_dependency_id bigint :=
    nullif(btrim(v_outbound->>'depends_on_id'), '')::bigint;
  v_mirror_applicable boolean;
  v_card_import_without_foreign boolean := false;
begin
  if v_action not in ('edit', 'delete', 'resolve', 'unresolve') then
    raise exception 'unsupported production comment lifecycle operation';
  end if;
  if v_requested_id is null or v_dedup_key is null or v_fingerprint is null then
    raise exception 'production comment lifecycle identity required';
  end if;

  select r.* into v_receipt
  from public.production_comment_mutation_receipts r
  where r.dedup_key = v_dedup_key;
  if found then
    if v_receipt.comment_id is distinct from v_requested_id
       or v_receipt.action is distinct from v_action
       or v_receipt.intent_fingerprint is distinct from v_fingerprint then
      raise exception 'idempotency_conflict';
    end if;
    select c.* into v_result
    from public.production_comments c
    where c.id = v_receipt.comment_id;
    if not found then raise exception 'idempotent_result_missing'; end if;
    return v_result;
  end if;

  select c.* into v_existing
  from public.production_comments c
  where c.id = v_requested_id
     or c.native_comment_id = v_requested_id
  order by case when c.id = v_requested_id then 0 else 1 end
  limit 1
  for update;
  if not found then raise exception 'comment_write_conflict'; end if;
  if p_expected_version is null or p_expected_updated_at is null
     or v_existing.version is distinct from p_expected_version
     or v_existing.updated_at is distinct from p_expected_updated_at then
    raise exception 'comment_write_conflict';
  end if;
  if v_existing.parent_id is not null and v_action in ('resolve', 'unresolve') then
    raise exception 'production comment root required';
  end if;

  v_target_id := coalesce(v_existing.deliverable_id, v_existing.batch_id);
  if v_target_id is null then raise exception 'production comment lifecycle target required'; end if;
  perform public.production_assert_authority(
    v_existing.client_slug,
    v_existing.team,
    coalesce((v_outbound->>'test_only')::boolean, false),
    v_legacy_parity
  );
  v_mirror_applicable := public.production_comment_mirror_applicable(
    coalesce((v_outbound->>'test_only')::boolean, false),
    v_legacy_parity
  );

  -- The CAS above proves the caller holds the current row, so a lifecycle
  -- edit/delete/resolve/reopen is a server-authoritative mutation. Clamp its
  -- source clock so it can never regress below the stored value. Without this a
  -- browser clock behind the row's source_updated_at — including a valid
  -- future-dated imported comment — would trip the production_comment_upsert
  -- stale-source guard, which returns the row unchanged; this function would
  -- then insert a mutation receipt and enqueue the old body, reporting (and
  -- letting exact retries replay) a false success for a write that never
  -- happened.
  v_comment := jsonb_set(
    v_comment,
    '{source_updated_at}',
    to_jsonb(greatest(
      coalesce(nullif(btrim(v_comment->>'source_updated_at'), '')::timestamptz, now()),
      v_existing.source_updated_at
    )::text),
    true
  );

  v_result := public.production_comment_upsert(v_comment, v_event - 'outbound');

  insert into public.production_comment_mutation_receipts (
    dedup_key, comment_id, action, intent_fingerprint, result_version
  ) values (
    v_dedup_key, v_result.id, v_action, v_fingerprint, v_result.version
  )
  on conflict (dedup_key) do nothing;
  if not found then raise exception 'idempotency_conflict'; end if;

  -- Linear has create/edit/delete mutations, but no native resolved state.
  -- Resolve/reopen therefore commits the canonical lifecycle and audit event
  -- without manufacturing a foreign comment or an inapplicable outbox row.
  if v_action in ('edit', 'delete') and v_mirror_applicable then
    -- Lifecycle writes never wait for the create mirror to bind a provider id.
    -- Instead each intent depends on the immediately preceding canonical
    -- comment intent. This preserves create -> edit(s) -> delete order while
    -- F2 is paused or Linear is unavailable, and lets the drainer hand the
    -- provider id forward from each durable predecessor receipt.
    select o.id into v_dependency_id
    from public.mirror_outbox o
    where o.entity = 'comment'
      and o.operation = 'comment'
      and o.comment_id = v_result.id
      and o.dedup_key <> v_dedup_key
      and o.status in ('pending', 'failed', 'shadow_ok', 'written', 'skipped')
    order by o.id desc
    limit 1;
    if v_supplied_dependency_id is not null
       and v_supplied_dependency_id is distinct from v_dependency_id then
      raise exception 'production comment dependency mismatch';
    end if;
    -- F42 rows were copied from native card arrays; the import itself never
    -- creates a Linear comment. Mark only an exact imported row that still has
    -- neither a provider id nor a predecessor intent. The drainer can then
    -- materialize a first edit as one create, or converge a first delete as a
    -- no-foreign-object terminal receipt, instead of retrying an impossible
    -- providerless edit/delete forever.
    select exists (
      select 1
      from public.production_comment_card_links l
      where l.production_comment_id = v_result.id
    )
      and v_result.linear_comment_id is null
      and v_dependency_id is null
    into v_card_import_without_foreign;
    v_payload := coalesce(v_outbound->'payload', '{}'::jsonb)
      || jsonb_build_object(
        'action', v_action,
        'body', v_result.body,
        'comment_id', v_result.id,
        'linear_comment_id', v_result.linear_comment_id,
        'card_import_without_foreign', v_card_import_without_foreign
      );
    v_outbox_id := public.mirror_outbox_enqueue(
      p_entity := 'comment',
      p_entity_id := v_target_id,
      p_operation := 'comment',
      p_payload := v_payload,
      p_dedup_key := v_dedup_key,
      p_source_edited_at := v_result.source_updated_at,
      p_client_slug := v_result.client_slug,
      p_team := v_result.team,
      p_actor := nullif(v_event->>'actor', ''),
      p_role := nullif(v_event->>'role', ''),
      p_deliverable_id := v_result.deliverable_id,
      p_batch_id := v_result.batch_id,
      p_comment_id := v_result.id,
      p_depends_on_id := v_dependency_id,
      p_test_only := coalesce((v_outbound->>'test_only')::boolean, false)
    );
    if v_legacy_parity then
      update public.mirror_outbox
      set legacy_parity = true, updated_at = now()
      where id = v_outbox_id;
    end if;
  end if;

  return v_result;
end;
$fn$;

revoke all on function public.production_comment_lifecycle_write(
  jsonb, jsonb, integer, timestamptz
) from public, anon, authenticated;
grant execute on function public.production_comment_lifecycle_write(
  jsonb, jsonb, integer, timestamptz
) to service_role;

create or replace function public.production_comment_card_import(
  p_link jsonb,
  p_comment jsonb,
  p_event jsonb default '{}'::jsonb
) returns public.production_comments
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_link jsonb := coalesce(p_link, '{}'::jsonb);
  v_comment jsonb := coalesce(p_comment, '{}'::jsonb);
  v_surface text := lower(nullif(btrim(v_link->>'source_surface'), ''));
  v_card_id text := nullif(btrim(v_link->>'card_id'), '');
  v_component text := lower(nullif(btrim(v_link->>'component'), ''));
  v_native_id text := nullif(btrim(v_link->>'native_comment_id'), '');
  v_deliverable_id text := nullif(btrim(v_link->>'deliverable_id'), '');
  v_client_slug text := nullif(btrim(v_link->>'client_slug'), '');
  v_link_team text := lower(nullif(btrim(v_link->>'team'), ''));
  v_fingerprint text := nullif(btrim(v_link->>'source_fingerprint'), '');
  v_comment_id text;
  v_target_team text;
  v_target_client_slug text;
  v_target_card_id text;
  v_target_origin text;
  v_expected_team text;
  v_existing_link public.production_comment_card_links%rowtype;
  v_result public.production_comments%rowtype;
begin
  if v_surface not in ('calendar', 'sxr')
     or v_card_id is null
     or v_component not in ('video', 'graphic', 'caption', 'title')
     or v_native_id is null
     or v_deliverable_id is null or v_client_slug is null
     or v_link_team not in ('video', 'graphics')
     or v_fingerprint is null then
    raise exception 'invalid production comment card import identity';
  end if;
  v_expected_team := case when v_component = 'graphic' then 'graphics' else 'video' end;
  select d.team, d.client_slug, d.card_id, d.origin
    into v_target_team, v_target_client_slug, v_target_card_id, v_target_origin
  from public.deliverables d
  where d.id = v_deliverable_id;
  if not found then raise exception 'production comment card import deliverable missing'; end if;
  if v_target_team is distinct from v_expected_team
     or v_link_team is distinct from v_target_team
     or v_client_slug is distinct from v_target_client_slug
     or v_card_id is distinct from v_target_card_id
     or v_target_origin is distinct from (
       case
         when v_surface = 'calendar' then 'calendar'
         else 'samples'
       end
     ) then
    raise exception 'production comment card import crosswalk mismatch';
  end if;

  select l.* into v_existing_link
  from public.production_comment_card_links l
  where l.source_surface = v_surface
    and l.card_id = v_card_id
    and l.component = v_component
    and l.native_comment_id = v_native_id
  for update;
  if found then
    if v_existing_link.deliverable_id is distinct from v_deliverable_id
       or v_existing_link.source_fingerprint is distinct from v_fingerprint then
      raise exception 'production comment card import identity conflict';
    end if;
    select c.* into v_result
    from public.production_comments c
    where c.id = v_existing_link.production_comment_id;
    return v_result;
  end if;

  v_comment_id := 'pc_card_' || encode(
    extensions.digest(
      v_surface || ':' || v_card_id || ':' || v_component || ':' || v_native_id,
      'sha256'
    ),
    'hex'
  );
  v_comment := v_comment
    || jsonb_build_object(
      'id', v_comment_id,
      -- Raw card ids are not globally unique. Preserve the raw identity in
      -- the crosswalk/provenance and use the composite canonical id here.
      'native_comment_id', v_comment_id,
      'deliverable_id', v_deliverable_id,
      'team', v_target_team,
      'origin', 'legacy',
      'source', 'backfill',
      'operation', 'upsert',
      'provenance', coalesce(v_comment->'provenance', '{}'::jsonb)
        || jsonb_build_object(
          'source_surface', v_surface,
          'card_id', v_card_id,
          'component', v_component,
          'native_comment_id', v_native_id
        )
    );
  v_result := public.production_comment_upsert(v_comment, coalesce(p_event, '{}'::jsonb));

  insert into public.production_comment_card_links (
    source_surface, card_id, component, native_comment_id,
    deliverable_id, production_comment_id, source_fingerprint
  ) values (
    v_surface, v_card_id, v_component, v_native_id,
    v_deliverable_id, v_result.id, v_fingerprint
  );
  return v_result;
end;
$fn$;

revoke all on function public.production_comment_card_import(jsonb, jsonb, jsonb)
  from public, anon, authenticated;
grant execute on function public.production_comment_card_import(jsonb, jsonb, jsonb)
  to service_role;

-- Service-only exact-count readback for the F42 apply runner. Returns the
-- number of card crosswalk links and their distinct canonical comments for a
-- backfill tag so the apply runner can verify applied == planned independently
-- of the RPC's own receipts. Body-free; exposes only two integers.
create or replace function public.production_comment_card_import_counts(
  p_backfill_tag text
) returns table (card_link_count bigint, comment_count bigint)
language sql
security definer
set search_path = public
as $fn$
  select
    count(*)::bigint as card_link_count,
    count(distinct l.production_comment_id)::bigint as comment_count
  from public.production_comment_card_links l
  join public.production_comments c on c.id = l.production_comment_id
  where c.backfill_tag = p_backfill_tag;
$fn$;

revoke all on function public.production_comment_card_import_counts(text)
  from public, anon, authenticated;
grant execute on function public.production_comment_card_import_counts(text)
  to service_role;

commit;
