#!/usr/bin/env node
/*
 * Regenerates supabase/functions/higgsfield-mcp/catalog.ts from Higgsfield's
 * public API docs (https://docs.higgsfield.ai/docs/llms-full.txt): one entry
 * per model endpoint with its name, a category, the usage notes and the input
 * JSON schema. The connector validates requests against these schemas.
 *
 *   node scripts/higgsfield-catalog.js            fetch the docs and rewrite
 *   node scripts/higgsfield-catalog.js <file>     use a saved copy instead
 */
'use strict';
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '..', 'supabase', 'functions', 'higgsfield-mcp', 'catalog.ts');
const SOURCE = 'https://docs.higgsfield.ai/docs/llms-full.txt';

function category(id) {
  if (/genjutsu\/motion|motion-control/.test(id)) return 'motion-transfer';
  if (/object-swap/.test(id)) return 'object-swap';
  if (/video-extend/.test(id)) return 'video-extend';
  if (/video-edit/.test(id)) return 'video-edit';
  if (/first-last-frame/.test(id)) return 'first-last-frame-video';
  if (/reference-to-video|image-reference|video-reference/.test(id)) return 'reference-to-video';
  if (/image-to-video/.test(id)) return 'image-to-video';
  if (/text-to-video/.test(id)) return 'text-to-video';
  if (/cinema-studio/.test(id)) return 'cinematic-video';
  if (/marketing-studio/.test(id)) return 'marketing-image';
  if (/qwen-image-3\/edit|grok-imagine-image/.test(id)) return 'image-edit';
  return 'text-to-image';
}

function strip(value) {
  if (Array.isArray(value)) return value.map(strip);
  if (value && typeof value === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(value)) if (k !== 'title') out[k] = strip(v);
    return out;
  }
  return value;
}

function parse(text) {
  const models = [];
  for (const sec of text.split(/\n(?=# )/)) {
    const id = (sec.match(/\*\*Endpoint ID:\*\* `([^`]+)`/) || [])[1];
    if (!id) continue;
    const name = sec.split('\n', 1)[0].slice(2).replace(/ API$/, '').trim();
    const notesBlock = (sec.match(/## Usage notes\n([\s\S]*?)\n## /) || [])[1] || '';
    const notes = notesBlock.split('\n').filter(l => l.startsWith('* ')).map(l => l.slice(2).replace(/\\/g, '').trim());
    const schemaText = (sec.match(/Complete JSON schema">\s*```json[^\n]*\n([\s\S]*?)```/) || [])[1];
    if (!schemaText) continue;
    models.push({ id, name, category: category(id), notes, schema: strip(JSON.parse(schemaText)) });
  }
  return models.sort((a, b) => a.id.localeCompare(b.id));
}

async function main() {
  const file = process.argv[2];
  const text = file ? fs.readFileSync(file, 'utf8') : await (await fetch(SOURCE)).text();
  const models = parse(text);
  if (models.length < 20) throw new Error('Parsed only ' + models.length + ' models; the docs format may have changed.');
  const body = '// Generated by scripts/higgsfield-catalog.js from ' + SOURCE + '. Do not hand-edit.\n\n'
    + 'export type CatalogModel = { id: string; name: string; category: string; notes: string[]; schema: Record<string, unknown> };\n\n'
    + 'export const CATALOG: CatalogModel[] = ' + JSON.stringify(models, null, 1) + ';\n';
  fs.writeFileSync(OUT, body);
  console.log('Wrote ' + path.relative(process.cwd(), OUT) + ': ' + models.length + ' models.');
}

main().catch(e => { console.error(e.message); process.exit(1); });
