begin read only;
set local search_path=public,pg_catalog;
select jsonb_build_object(
 'schema',(select jsonb_build_object('owner',pg_get_userbyid(nspowner),'acl',nspacl::text) from pg_namespace where nspname='public'),
 'server_major',current_setting('server_version_num')::integer/10000,
 'tables',(select coalesce(jsonb_agg(jsonb_build_object(
  'name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'persistence',c.relpersistence,'replica_identity',c.relreplident,'options',c.reloptions,'access_method',am.amname,'partition_key_md5',md5(pg_get_partkeydef(c.oid)),
  'columns',(select jsonb_agg(jsonb_build_object('position',a.attnum,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'acl',a.attacl::text,'collation',case when a.attcollation=0 then null else a.attcollation::regcollation::text end,'default_md5',md5(pg_get_expr(d.adbin,d.adrelid))) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),
  'constraints',(select coalesce(jsonb_agg(jsonb_build_object('name',k.conname,'type',k.contype,'validated',k.convalidated,'deferrable',k.condeferrable,'initially_deferred',k.condeferred,'columns',k.conkey,'foreign_columns',k.confkey,'definition_md5',md5(pg_get_constraintdef(k.oid))) order by k.conname),'[]'::jsonb) from pg_constraint k where k.conrelid=c.oid)
 ) order by c.relname),'[]'::jsonb) from pg_class c left join pg_am am on am.oid=c.relam where c.relnamespace='public'::regnamespace and c.relkind in ('r','p')),
 'functions',(select coalesce(jsonb_agg(jsonb_build_object('name',p.proname,'arguments',pg_get_function_identity_arguments(p.oid),'result',pg_get_function_result(p.oid),'kind',p.prokind,'language',l.lanname,'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'body_raw_md5',md5(p.prosrc),'definition_raw_md5',md5(pg_get_functiondef(p.oid)),'body_lf_md5',md5(replace(p.prosrc,chr(13),'')),'definition_lf_md5',md5(replace(pg_get_functiondef(p.oid),chr(13),'')),'volatility',p.provolatile,'security_definer',p.prosecdef,'strict',p.proisstrict,'leakproof',p.proleakproof,'parallel',p.proparallel,'config',p.proconfig,'service_execute',has_function_privilege('service_role',p.oid,'EXECUTE'),'anon_execute',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticated_execute',has_function_privilege('authenticated',p.oid,'EXECUTE')) order by p.proname,pg_get_function_identity_arguments(p.oid)),'[]'::jsonb) from pg_proc p join pg_language l on l.oid=p.prolang where p.pronamespace='public'::regnamespace and p.prokind in ('f','p')),
 'views',(select coalesce(jsonb_agg(jsonb_build_object('name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'options',c.reloptions,'definition_md5',md5(pg_get_viewdef(c.oid,true))) order by c.relname),'[]'::jsonb) from pg_class c where c.relnamespace='public'::regnamespace and c.relkind in ('v','m')),
 'sequences',(select coalesce(jsonb_agg(jsonb_build_object('name',c.relname,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'type',format_type(s.seqtypid,null),'start',s.seqstart::text,'increment',s.seqincrement::text,'minimum',s.seqmin::text,'maximum',s.seqmax::text,'cache',s.seqcache::text,'cycle',s.seqcycle) order by c.relname),'[]'::jsonb) from pg_sequence s join pg_class c on c.oid=s.seqrelid where c.relnamespace='public'::regnamespace),
 'indexes',(select coalesce(jsonb_agg(jsonb_build_object('table',t.relname,'name',c.relname,'definition_md5',md5(pg_get_indexdef(c.oid)),'unique',i.indisunique,'primary',i.indisprimary,'valid',i.indisvalid,'ready',i.indisready,'clustered',i.indisclustered,'replica_identity',i.indisreplident,'nulls_not_distinct',i.indnullsnotdistinct) order by t.relname,c.relname),'[]'::jsonb) from pg_index i join pg_class c on c.oid=i.indexrelid join pg_class t on t.oid=i.indrelid where t.relnamespace='public'::regnamespace),
 'triggers',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'name',t.tgname,'internal',t.tgisinternal,'definition_md5',md5(pg_get_triggerdef(t.oid)),'enabled',t.tgenabled,'deferrable',t.tgdeferrable,'initially_deferred',t.tginitdeferred) order by c.relname,t.tgname),'[]'::jsonb) from pg_trigger t join pg_class c on c.oid=t.tgrelid where c.relnamespace='public'::regnamespace and not t.tgisinternal),
 'internal_constraint_triggers',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'constraint',k.conname,'type',t.tgtype,'function',t.tgfoid::regprocedure::text,'enabled',t.tgenabled,'deferrable',t.tgdeferrable,'initially_deferred',t.tginitdeferred) order by c.relname,k.conname,t.tgtype,t.tgfoid::regprocedure::text),'[]'::jsonb) from pg_trigger t join pg_class c on c.oid=t.tgrelid left join pg_constraint k on k.oid=t.tgconstraint where c.relnamespace='public'::regnamespace and t.tgisinternal),
 'policies',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'name',p.polname,'command',p.polcmd,'permissive',p.polpermissive,'roles',(select jsonb_agg(case when role_oid=0 then 'public' else pg_get_userbyid(role_oid) end order by case when role_oid=0 then 'public' else pg_get_userbyid(role_oid) end) from unnest(p.polroles) role_oid),'using_md5',md5(pg_get_expr(p.polqual,p.polrelid)),'check_md5',md5(pg_get_expr(p.polwithcheck,p.polrelid))) order by c.relname,p.polname),'[]'::jsonb) from pg_policy p join pg_class c on c.oid=p.polrelid where c.relnamespace='public'::regnamespace),
 'rules',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'name',r.rulename,'enabled',r.ev_enabled,'definition_md5',md5(pg_get_ruledef(r.oid))) order by c.relname,r.rulename),'[]'::jsonb) from pg_rewrite r join pg_class c on c.oid=r.ev_class where c.relnamespace='public'::regnamespace),
 'types',(select coalesce(jsonb_agg(jsonb_build_object('name',t.typname,'kind',t.typtype,'owner',pg_get_userbyid(t.typowner),'acl',t.typacl::text,'base',format_type(t.typbasetype,t.typtypmod),'not_null',t.typnotnull,'default_md5',md5(t.typdefault),'constraints',(select coalesce(jsonb_agg(jsonb_build_object('name',k.conname,'definition_md5',md5(pg_get_constraintdef(k.oid)),'validated',k.convalidated) order by k.conname),'[]'::jsonb) from pg_constraint k where k.contypid=t.oid),'enum_labels',(select jsonb_agg(e.enumlabel order by e.enumsortorder) from pg_enum e where e.enumtypid=t.oid)) order by t.typname),'[]'::jsonb) from pg_type t where t.typnamespace='public'::regnamespace and t.typtype in ('d','e')),
 'default_acls',(select coalesce(jsonb_agg(jsonb_build_object('role',pg_get_userbyid(d.defaclrole),'kind',d.defaclobjtype,'acl',d.defaclacl::text) order by pg_get_userbyid(d.defaclrole),d.defaclobjtype),'[]'::jsonb) from pg_default_acl d where d.defaclnamespace='public'::regnamespace),
 'publications',(select coalesce(jsonb_agg(jsonb_build_object('name',p.pubname,'owner',pg_get_userbyid(p.pubowner),'all_tables',p.puballtables,'insert',p.pubinsert,'update',p.pubupdate,'delete',p.pubdelete,'truncate',p.pubtruncate,'via_root',p.pubviaroot,'public_schema',(select exists(select 1 from pg_publication_namespace n where n.pnpubid=p.oid and n.pnnspid='public'::regnamespace)),'tables',(select coalesce(jsonb_agg(jsonb_build_object('name',c.relname,'columns',r.prattrs::text,'filter_md5',md5(pg_get_expr(r.prqual,r.prrelid))) order by c.relname),'[]'::jsonb) from pg_publication_rel r join pg_class c on c.oid=r.prrelid where r.prpubid=p.oid and c.relnamespace='public'::regnamespace)) order by p.pubname),'[]'::jsonb) from pg_publication p where p.puballtables or p.pubname='supabase_realtime' or exists(select 1 from pg_publication_namespace n where n.pnpubid=p.oid and n.pnnspid='public'::regnamespace) or exists(select 1 from pg_publication_rel r join pg_class c on c.oid=r.prrelid where r.prpubid=p.oid and c.relnamespace='public'::regnamespace)),
 'dependencies',(select coalesce(jsonb_agg(jsonb_build_object('object_type',o.type,'object',o.identity,'referenced_type',r.type,'referenced',r.identity,'kind',d.deptype) order by o.type,o.identity,r.type,r.identity,d.deptype),'[]'::jsonb) from pg_depend d cross join lateral pg_identify_object(d.classid,d.objid,d.objsubid) o cross join lateral pg_identify_object(d.refclassid,d.refobjid,d.refobjsubid) r where o.schema='public' and not (d.classid='pg_trigger'::regclass and exists(select 1 from pg_trigger z where z.oid=d.objid and z.tgisinternal)))
);
commit;
