'use strict';
const fs=require('fs'),path=require('path');
const {runReconcile,publicReport,assessSummary}=require('./reconcile-lib');
const ROOT=path.resolve(__dirname,'..','..');
const RPC_NAMES=new Set(['production_intake_reconcile_backlog','production_intake_reconcile_children','production_intake_reconcile_cards','production_intake_reconcile_summary']);
function argsFor(argv){return new Map(argv.map(a=>{const m=String(a).match(/^--([^=]+)(?:=(.*))?$/);return m?[m[1],m[2]==null?'1':m[2]]:[a,'1'];}));}
function parseIntOption(raw,name,{min=0,max=Number.MAX_SAFE_INTEGER,required=false}={}){if(raw===undefined||raw===''){if(required)throw publicError('config_error:'+name);return undefined;}if(!/^\d+$/.test(String(raw)))throw publicError('config_error:'+name);const value=Number(raw);if(!Number.isSafeInteger(value)||value<min||value>max)throw publicError('config_error:'+name);return value;}
function publicError(code){const error=new Error(code);error.publicCode=code;return error;}
function textuallyInside(relative){return relative===''||(!path.isAbsolute(relative)&&relative!=='..'&&!relative.startsWith('..'+path.sep));}
function insideRepository(target){const resolved=path.resolve(target);let rootReal;try{rootReal=fs.realpathSync(ROOT);}catch(_){return true;}if(textuallyInside(path.relative(ROOT,resolved))||textuallyInside(path.relative(rootReal,resolved)))return true;let probe=resolved,tail=[];while(!fs.existsSync(probe)){tail.unshift(path.basename(probe));const parent=path.dirname(probe);if(parent===probe)return true;probe=parent;}let real;try{real=fs.realpathSync(probe);}catch(_){return true;}if(textuallyInside(path.relative(rootReal,path.join(real,...tail))))return true;try{if(fs.lstatSync(resolved).isSymbolicLink())return true;}catch(_){}return false;}
class RpcError extends Error{constructor(name,status,detail,code){super(code||`rpc_failed:${RPC_NAMES.has(name)?name:'unknown'}:http_${Number(status)||0}`);this.publicCode=this.message;this.detail=detail;}}
function restTransport({url,key,timeoutMs}){return async function restRpc(name,params){if(!RPC_NAMES.has(name))throw new RpcError(name,0,'','rpc_failed:unknown');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);let response,text;try{response=await fetch(`${url}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(params||{}),signal:controller.signal});text=await response.text();}catch(error){if(error&&error.name==='AbortError')throw new RpcError(name,0,'','rpc_timeout:'+name);throw new RpcError(name,0,'','rpc_transport:'+name);}finally{clearTimeout(timer);}if(!response.ok)throw new RpcError(name,response.status,text.slice(0,2000));try{return text?JSON.parse(text):null;}catch(_){throw new RpcError(name,0,text.slice(0,2000),'rpc_malformed:'+name);}};}
function healthLimits(args){return {maxBacklogAgeSeconds:parseIntOption(args.get('max-backlog-age-seconds'),'max_backlog_age_seconds',{min:0,max:31536000}),maxRequestsOwed:parseIntOption(args.get('max-requests-owed'),'max_requests_owed',{min:0,max:1000000}),maxMissingTerminalReceipts:parseIntOption(args.get('max-missing-terminal-receipts'),'max_missing_terminal_receipts',{min:0,max:1000000}),maxIdentityConflicts:parseIntOption(args.get('max-identity-conflicts'),'max_identity_conflicts',{min:0,max:1000000})};}
async function main(config,argv=process.argv.slice(2),env=process.env){const args=argsFor(argv),apply=args.has('apply'),strict=args.has('strict'),limit=parseIntOption(args.get('limit')||'25','limit',{min:1,max:500,required:true}),requestIds=String(args.get('request-id')||'').split(',').map(s=>s.trim()).filter(Boolean),actor=String(args.get('actor')||env[config.actorEnv]||config.actor).trim(),privateRaw=String(args.get('private-report')||''),hashKey=String(env[config.hashEnv]||''),url=String(env.SUPABASE_URL||'').replace(/\/$/,''),key=String(env.SUPABASE_SERVICE_ROLE_KEY||''),timeoutMs=parseIntOption(env.NATIVE_INTAKE_RPC_TIMEOUT_MS||'15000','rpc_timeout_ms',{min:1000,max:60000,required:true});
 if(!url||!key)throw publicError('config_error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required');if(apply&&env[config.confirmEnv]!=='RECONCILE_NATIVE_INTAKE_APPLY')throw publicError('config_error: --apply requires '+config.confirmEnv+'=RECONCILE_NATIVE_INTAKE_APPLY');if(!actor)throw publicError('config_error: actor_required');let privatePath='';if(privateRaw){privatePath=path.resolve(privateRaw);if(insideRepository(privatePath))throw publicError('config_error: refusing to write the private report inside the repository');}
 let report=null,failure=null;try{report=await runReconcile({rpc:restTransport({url,key,timeoutMs}),actor,apply,limit,requestIds,onEvent:(stage,entry)=>{if(!hashKey)return;const {correlation,boundOutcome}=require('./reconcile-lib');console.error(`${apply?'apply':'plan '} ${stage.padEnd(8)} ${correlation(entry.request_id,hashKey)} -> ${boundOutcome((entry[stage]||{}).outcome)}`);}});}catch(error){failure=error;}
 if(privatePath){fs.writeFileSync(privatePath,JSON.stringify({report,failure:failure?{code:failure.publicCode||'runner_failed',detail:failure.detail||String(failure&&failure.message||'')}:null,written_at:new Date().toISOString()},null,2),{mode:0o600});console.error('private report written outside the repository');}
 if(failure)throw failure;const pub=publicReport(report,{hashKey});console.log(JSON.stringify(pub,null,2));if(strict&&apply){const health=assessSummary(report.summary,healthLimits(args));if(pub.attention.conflicted>0||pub.attention.unresolved>0||report.limited||!health.ok){const error=publicError('reconcile_attention_required');error.exitCode=3;throw error;}}return pub;}
function run(config){main(config).catch(error=>{console.error(String(error.publicCode||'runner_failed'));process.exit(error.exitCode||1);});}
module.exports={main,run,restTransport,argsFor,healthLimits,insideRepository,parseIntOption};
